//
//  CBDContactsController.m
//  Contacts-Hybrid
//
//  Created by Christopher Devito on 5/18/20.
//  Copyright © 2020 Lambda, Inc. All rights reserved.
//

#import "CBDContactsController.h"
//#import "Contacts.swift" // Error: Doesn't work!

// use the autogenerated swift header for our classes
#import "Contacts_Hybrid-Swift.h"

@implementation CBDContactsController

// lazy array
// when we use readonly and getter is overridden, we need to synthezise variable
@synthesize contacts = _contacts;
- (NSArray<Contact *> *)contacts {
    if (!_contacts) {
        _contacts = @[
            [[Contact alloc] initWithName:@"Christopher" relationship:@"Me"],
            [[Contact alloc] initWithName:@"Lucas" relationship:@"Son"],
        ];
    }
    return _contacts;
}

- (instancetype)init {
    self = [super init];
    if (self) {

    }
    return self;
}

@end
